### ISSUE TITLE
PlayerInteractEvent does not work as expected

### ISSUE THREAD

**Issue by kvetinac97** [yescallop/Nukkit#13]
Don't know if it's MCPE's bug, but when you have e.g. a compass in your hand and you:

1. Hold screen on air and call PlayerInteractEvent with ACTION_RIGHT_CLICK, that's good

2. Tap on chest, ender chest, button, lever or any tile or block that has a reaction in vanilla (chest opens, button emits redstone signal...), it works.

3. Tap on dirt, cobblestone, hardened clay, just any block which does not react to you clicking it in Vanilla, event doesn't work (so probably MCPE does not sent it). Block breaking works.

So the problem probably is always in CanPlaceOn/CanDestroy, or...?

**Comment by boybook** [comment]
I had a debug test and did what you said. Here is the debug messages and all worked fine. Is it because of your plugins?
<img width="1298" alt="qq20170606-171808 2x" src="https://cloud.githubusercontent.com/assets/8210983/26822401/777b9436-4adc-11e7-9e3e-0d692d6c866a.png">

**Comment by kvetinac97** [comment]
Ya, got it fixed
