### ISSUE TITLE
Chunks aren't saving once edited

### ISSUE THREAD

**Issue by pixelzee** [yescallop/Nukkit#14]
Loaded up a map then placed blocks at spawn.  Travelled 500 blocks away from spawn so the chunk would unload and then teleported back to spawn and the blocks dissipated.

No errors in console.

**Comment by boybook** [comment]
I did the test, but it not happened. What format of your map? Did you turn off the auto-save?

**Comment by pixelzee** [comment]
I didn't know there was a boolean for auto-save,
let me force auto-save on and get back to you

**Comment by pixelzee** [comment]
sorry, it was disabled in config

**Comment by pixelzee** [comment]
works now
