### ISSUE TITLE
Old world visible when teleporting to new world

### ISSUE THREAD

**Issue by TDS200** [yescallop/Nukkit#15]
### Issue description

When teleporting to another level/world it doesn't seem to work. But, if you place a block or something else triggers a chunk update (lightning) that particular chunk reloads to what it should be.

### Steps to reproduce the issue

1. Teleport to a different world/level.

### OS and versions

* Nukkit Version: 1.0dev (protocol version 113) 
 
* Java Version: 1.8

* Host OS: Windows

* Host Configuration: 12 GB RAM,  500 GB HDD(SSD/HDD/...) drive, 4 core CPU from Intel(Intel/AMD/...), 7 Mb internet upload

* Client Edition: Windows 10

* Client Version: 1.1.0

**Comment by imjack** [comment]
This is an issue related to mcpe not something that I know nukkit can fix. One method is to teleport the player a few chunks away then teleport them back.

**Comment by boybook** [comment]
These codes are already in Nukkit, but I don't know why it didn't work now.

**Comment by TDS200** [comment]
@boybook  I tried teleporting far away and then back and it does fix the issue. I don't know if this is related to the issue or not. But, that glitch that rarely happens when joining or teleporting happens a lot more after the update. (The one where you get stuck in the void and everything starts going crazy on your screen)

**Comment by ghost** [comment]
![tim 20170610015952](https://user-images.githubusercontent.com/16436412/26988161-d09f7e0a-4d80-11e7-8aac-dc8dda6354ba.png)
![tim 20170610020034](https://user-images.githubusercontent.com/16436412/26988163-d0aeffe2-4d80-11e7-8568-036bf4cbbdfe.png)


Like this

**Comment by Bedrocks** [comment]
I have the same issue :c

**Comment by Goodstuff4UonYT** [comment]
Me too

**Comment by jrodr10** [comment]
I just mess with my display options and it works lol

**Comment by jrodr10** [comment]
Ik what you're thinking.. "why should I have to move my render distance up and down to play on my other world ;-; #Nether #Kms #ImHungryNow #Gtg

**Comment by Snake1999** [comment]
+1. Need a way to clean client buffered world data (?)

I hate the statement called "chunks".

**Comment by Goodstuff4UonYT** [comment]
@Snake1999 @boybook I think this bug is very important.

**Comment by boybook** [comment]
You need ChamgeDimensionPacket to sovle it.

**Comment by Goodstuff4UonYT** [comment]
@boybook okey thanks!

**Comment by boybook** [comment]
Send ChangeDimensionPacket with dimension 1,
Send PlayStatusPacket with PLAYER_SPAWN,
Send some empty chunks around players,
Wait some ticks until client receive all chunks,
Send ChangeDimensionPacket with dimension 0,
Start to send real chunks data.
Send PlayStatusPacket with PLAYER_SPAWN.

**Comment by Goodstuff4UonYT** [comment]
@boybook .__.

**Comment by Goodstuff4UonYT** [comment]
@boybook I think I get it. I will try it. Thanks!

**Comment by boybook** [comment]
@Goodstuff4UonYT There must be a time difference between all the steps.

**Comment by Snake1999** [comment]
To finish up this issue, we should, implement this method into Nukkit itself

**Comment by Goodstuff4UonYT** [comment]
@Snake1999 That would be nice!

**Comment by Goodstuff4UonYT** [comment]
@boybook Do you implement this method?

**Comment by Goodstuff4UonYT** [comment]
@boybook It does not work but I think I did something wrong.

**Comment by Creeperface01** [comment]
@boybook @Goodstuff4UonYT just tested this workaround and works perfectly! I'll push it to this fork

**Comment by Snake1999** [comment]
@Creeperface01 :) Great

**Comment by Creeperface01** [comment]
Fixed in https://github.com/yescallop/Nukkit/commit/b7e6c297edeb487d0430708368caa8e1b7aac063
