### ISSUE TITLE
Resource Packs not downloading to client.

### ISSUE THREAD

**Issue by TDS200** [yescallop/Nukkit#16]
### Issue description

When joining a server that has a resource pack. Everything works great. The server loads the pack with no problem. But when the client clicks the download resource pack button, they get this message as they are disconnected: "logged out due to Encountered a problem while downloading or applying resource pack".

### Steps to reproduce the issue

1. Add a resource pack to your server.
2. Try to join.

### OS and versions

* Nukkit Version: 1.0dev
 
* Java Version: 1.8

* Host OS: Windows

* Host Configuration: 12 GB RAM,  500 GB HDD(SSD/HDD/...) drive, 4 core CPU from Intel(Intel/AMD/...), 7 Mb internet upload

* Client Edition: Windows 10

* Client Version: 1.1.0

**Comment by Creeperface01** [comment]
Maybe your resource pack is corrupted?

**Comment by TDS200** [comment]
@Creeperface01  I don't think so. The resource pack I made only changes 3 or 4 blocks. Plus, I've tried to use the default resource pack from Minecraft "https://minecraft.net/en-us/addons/" and it still fails.

**Comment by Snake1999** [comment]
Confirmed. 
This issue will be closed (instead, go to master branch)

**Comment by Snake1999** [comment]
@TDS200 Fixed at https://github.com/yescallop/Nukkit/commit/bf26ae9e7edd457112599a03d8dcd278f0d2ddf6
