### ISSUE TITLE
Signs are not always correctly loaded

### ISSUE THREAD

**Issue by imjack** [yescallop/Nukkit#18]
### Issue description

I am using a plugin to store the locations of certain signs. Once the server restarts and loads them the plugin/nukkit doesn't recognize they are there.

### Steps to reproduce the issue
Using this code to check if the Sign is there: https://hastebin.com/kapekipebu.rb . To debug the problem I created multiple signs which where added to the arenaSigns List. If the sign wasn't reccognised to be there the block ID and the location is printed.

My debug area: 
![debug area](https://user-images.githubusercontent.com/4912609/26952613-2c84c7ea-4c9e-11e7-9610-e9f08da4604a.png)
This is printed:
Block ID: 0 Location (level=world, x=130.0, y=72.0, z=155.0, yaw=0.0, pitch=0.0)
Block ID: 0 Location (level=world, x=129.0, y=72.0, z=155.0, yaw=0.0, pitch=0.0)
Although this image shows the sign in fact being there:
![sign bug](https://user-images.githubusercontent.com/4912609/26952638-4b12bd02-4c9e-11e7-990f-d363e9ea7025.png)
Another issue with signs is that they will randomly disappear as if a block wasn't placed. 

### OS and versions

* Nukkit Version:  This server is running Nukkit 1.0dev 「蘋果(Apple)派(Pie)」 implementing API version 1.0.0 for Minecraft: PE v1.1.0 (protocol version 113)
 
* Java Version: 

* Host OS: Win10

* Client Edition: Win 10

* Client Version: 1.1.0

**Comment by Creeperface01** [comment]
Then you probably store bad coordinates :D I havent this problem and I store a lot of signs

**Comment by Creeperface01** [comment]
Or does it happen since 1.1?

**Comment by Creeperface01** [comment]
Try to teleport to 129.5, 72, 155.5

**Comment by jrodr10** [comment]
Though when the maps are uploaded the cords will be different for the signs,

**Comment by imjack** [comment]
This has happened on the last update also. I can't understand why I have this issue.

**Comment by jrodr10** [comment]
shouldnt it be Blocks.STANDING_SIGN?

**Comment by Snake1999** [comment]
@jrodr10 This is NOT forge

**Comment by jrodr10** [comment]
._. jus makes sense to me i guess .-. sorry dad @Snake1999

**Comment by yescallop** [comment]
If issue still exists, please go to the original repository (https://github.com/Nukkit/Nukkit) to ask for help.
