### ISSUE TITLE
Logging in procedure cause client crashes

### ISSUE THREAD

**Issue by ghost** [yescallop/Nukkit#19]
When connect to the server, the client crashes 
### Steps to reproduce the issue

1. start server 
2. join in

### OS and versions

* Nukkit Version: [https://github.com/yescallop/Nukkit/commit/821ce64226abb18b832e36043229c224c465f3b4](url)

* Java Version: 8

* Host OS:  Windows Server 2016

* Host Configuration: 32GB RAM, 80GB SSD drive, 24 cores CPU from Intel , 15 Mb internet upload

* Client Edition: Windows 10 and Android

* Client Version: 1.1.0

**Comment by yescallop** [comment]
Cannot reproduce on Android v1.1.0.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/16436412/26999812-1dd9c730-4dd5-11e7-9438-8f4b9ef2ff79.png)

**Comment by beito123** [comment]
ummm... I sometimes see the same bug too, but I will that can join to the server after a while.
(it might be a bug by resourcepack)

**Comment by ghost** [comment]
But I didn't install resourcepack   ...   
![image](https://user-images.githubusercontent.com/16436412/27000766-d997cb82-4deb-11e7-9f96-8c0066192674.png)

**Comment by Goodstuff4UonYT** [comment]
Have the same issue

**Comment by Goodstuff4UonYT** [comment]
@yescallop Android crashs in 1 of 20 times, win10 in 3 of 5.

**Comment by Snake1999** [comment]
Can not reproduce by me after many of trials in Samsung Note 3 (50 times) and iPhone 5S (50 times).
I have installed one resource pack sized 1.1MiB and have them downloaded by the client every time.

### OS and versions

* Nukkit Version: [https://github.com/yescallop/Nukkit/commit/821ce64226abb18b832e36043229c224c465f3b4](url)

* Java Version: 8

* Host OS:  Windows 10

* Host Configuration: 8GB RAM, 2TB Hard Disk Drive, 4 cores CPU from Intel , 100 Mb internet upload

* Client Version: 1.1.0

**Comment by Goodstuff4UonYT** [comment]
@Snake1999 Can you test it with Win10?

**Comment by ghost** [comment]
Now find a way           
Before you join the server, cancel your OP and join it should not crash

**Comment by Goodstuff4UonYT** [comment]
@lsw46 What do you mean with "cancel your OP"?

**Comment by ghost** [comment]
：- |

**Comment by ghost** [comment]
Just cancel the OP and then join the server, it probably won't crash...   
in Windows 10 😰

**Comment by yescallop** [comment]
@Goodstuff4UonYT He means make the player not an operator

**Comment by Goodstuff4UonYT** [comment]
@yescallop @lsw46 okey thanks, I will try it.

**Comment by Goodstuff4UonYT** [comment]
@yescallop @lsw46 Thanks, it works now.

**Comment by ghost** [comment]
@Snake1999 How do you send resourcepack to the client? I couldn't find the code for sending resourcepack to the player. :/

**Comment by boybook** [comment]
I found this bug yesterday. Using version https://github.com/yescallop/Nukkit/commit/e60aa14698213acc8cb17afc3efb9b85a6155d19
Then I tried Nemisys which use old version of network(from https://github.com/yescallop/Nukkit/commit/d49318fbd6e9e7f44c935390a89ab2be307ff15c)
,my client didn't crash.

**Comment by Snake1999** [comment]
I didn't know what ‘crash’ means... The buzzy client won't give us a crash report

**Comment by boybook** [comment]
I did a test for this, as long as do Thread.sleep(pause) a short time after sending StartGamePacket, the game will not crash again.
Please personally test to determine the correctness of this discovery.

**Comment by CraftYourBukkit** [comment]
But before 1.1 it didn't crash :/ 
Isn't there any fix for that? Couldn't we fix it in the software?

**Comment by CraftYourBukkit** [comment]
Is there a way to check if PlayerJoinEvent is done?

**Comment by Creeperface01** [comment]
CraftYourBukkit said we should ban this faker :D

**Comment by CraftYourBukkit** [comment]
What do u mean?

**Comment by Creeperface01** [comment]
you are fake craftYourBukkit :D

**Comment by CraftYourBukkit** [comment]
No? lol. But what's with my question?

**Comment by Creeperface01** [comment]
Yes you are :D https://github.com/BukkitPlaysMC this is real CraftYourBukkit :D

**Comment by CraftYourBukkit** [comment]
I don't know him :/ and I can name myself how I want.

**Comment by CraftYourBukkit** [comment]
And what's with my question? :/

**Comment by yescallop** [comment]
If issue still exists, please go to the original repository (https://github.com/Nukkit/Nukkit) to ask for help.
