### ISSUE TITLE
Items bug

### ISSUE THREAD

**Issue by Creeperface01** [yescallop/Nukkit#20]
something is wrong with items sending probably (white beds, black terracottas), in creative inventory

**Comment by yescallop** [comment]
@Creeperface01 I tried fixing beds in https://github.com/yescallop/Nukkit/commit/68be11c66cc77c18ed98c3eb576dbdc95d09753a, but all creative items just disappears.
It's supposed to be due to incorrect slot nbt writing, trying to figure it out

**Comment by yescallop** [comment]
Fixed in https://github.com/yescallop/Nukkit/commit/6c69acb38052676ce9ab6383a17c67df41390a2d and https://github.com/yescallop/Nukkit/commit/6b3762e48349374ff87d6f8f8a7423c1f53c4991
