### ISSUE TITLE
NullPointerException while sending CommandData

### ISSUE THREAD

**Issue by ghost** [yescallop/Nukkit#21]
### Issue description
NullPointerException while sending CommandData

### Steps to reproduce the issue

(This happened one time only)
1. Build Server from src
2. Start Server
3. Join server (I used win10 edition)

### OS and versions
* Nukkit Version:  Nukkit 1.0dev ???(Apple)?(Pie)? implementing API version 1.0.0 for Minecraft: PE
v1.1.0 (protocol version 113)
* Java Version: java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
* Host OS: Windows 10
* Host Configuration: 16 GB RAM, 256 GB SSD drive, 8 core CPU from AMD, Local  Server lol
* Client Edition: Win 10
* Client Version: 1.1.0

![code](https://user-images.githubusercontent.com/12514047/27006531-714f8484-4e36-11e7-8eb7-7136e7bc3485.PNG)
![consoo](https://user-images.githubusercontent.com/12514047/27006532-71656f6a-4e36-11e7-9e71-208f2ed6e6c3.PNG)

**Comment by yescallop** [comment]
@Godsoft029 Fixed at https://github.com/yescallop/Nukkit/commit/68e30a3326b54643f5dbe67d96ab93fa64a83fb2
