### ISSUE TITLE
Bed becomes white after being placed

### ISSUE THREAD

**Issue by yescallop** [yescallop/Nukkit#22]
As title, using Nukkit at https://github.com/yescallop/Nukkit/commit/256769c1ce0a0613430716c6f037a29e257f0833
Rejoining the server makes the bed return to original color

**Comment by Creeperface01** [comment]
maybe somthing with nbt sending :D I had similar issue with pistons I sent right nbt but piston became invisible after join

**Comment by Snake1999** [comment]
+1
