### ISSUE TITLE
Crafting in pocket mode

### ISSUE THREAD

**Issue by imjack** [yescallop/Nukkit#25]
### Issue description

Crafting certain items don't work in the pocket GUI mode.
### Steps to reproduce the issue

1. ... Get a diamond block and try uncraft it in pocket mode you won't be able to. Although in classic mode you can uncraft it. Other players have reported other items not being craftable too.

### OS and versions

* Nukkit Version: https://github.com/yescallop/Nukkit/commit/bad722f9a1db2b7dac4a9789f1e65bb272bb5293
 
* Java Version: 8

* Host OS: win10

* Host Configuration: ?? GB RAM, ?? GB ??(SSD/HDD/...) drive, ?? core CPU from ??(Intel/AMD/...), ?? Mb internet upload

* Client Edition: win 10

* Client Version: 1.1.0

**Comment by deathspawn** [comment]
This happens on Pocket Edition too. Can't create a furnace unless you are using classic mode.

**Comment by Snake1999** [comment]
Blame @shoghicp. We are doing works replacing old system

**Comment by Creeperface01** [comment]
I also noticed that I can craft some items in classic GUI, but I dont get the result

**Comment by yescallop** [comment]
If issue still exists, please go to the original repository (https://github.com/Nukkit/Nukkit) to ask for help.
