### ISSUE TITLE
Download plz?

### ISSUE THREAD

**Issue by MalakasPlayzMC** [yescallop/Nukkit#26]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ...
2. ...
3. ...

### OS and versions

* Nukkit Version: ?? 
 
* Java Version: ??

* Host OS: ??

* Host Configuration: ?? GB RAM, ?? GB ??(SSD/HDD/...) drive, ?? core CPU from ??(Intel/AMD/...), ?? Mb internet upload

* Client Edition: ??

* Client Version: ??.??.??

### Crashdump, backtrace or other files

* 
```
<!--- Copy and paste your backtrace here... -->
```
* ...

**Comment by Goodstuff4UonYT** [comment]
You can find a download link in this issue : https://github.com/Nukkit/Nukkit/issues/1743
