### ISSUE TITLE
Farmland bug!!

### ISSUE THREAD

**Issue by CraftYourBukkit** [yescallop/Nukkit#29]
Sry for reopening 

"I found a bug

Nukkit version: newest and the versions before

Description:
If I cancel the BlockBreakEvent and a player jumps on farmland the farmland gets destroyed.
"

-> I don't meant destroying the block by clicking on it. I meant jumping on the block. PlayerInteractEvent isn't called!

**Comment by Creeperface01** [comment]
it is called

**Comment by CraftYourBukkit** [comment]
No. I tested it with event.getBlock().getName() onInteract. But it didn't get called

**Comment by Creeperface01** [comment]
This is not php

**Comment by CraftYourBukkit** [comment]
I wrote it wrong in here. In my code it's in java

**Comment by yescallop** [comment]
Try again, interact action is PHYSICAL

**Comment by CraftYourBukkit** [comment]
But how can I cancel the jump breaking of farmland?

**Comment by Creeperface01** [comment]
event.setCancelled()
