### ISSUE TITLE
Client have crash when trying to join server

### ISSUE THREAD

**Issue by rusinc** [yescallop/Nukkit#37]
### Issue description

When i try to join server, my MCPE and MC:win10ed has crash.
Server have no plugins. properties is set as default.
### OS and versions

* Nukkit Version: Nukkit 1.0dev「 蘋果(Apple)派(Pie)」 ,API version 1.0.0 for Minecraft: PE v1.1.0 (protocol version 113)
 
* Java Version: 8

* Host OS: Win10/Ubuntu

* Host Configuration: 16 GB RAM, 120 GB SSD drive, 4 core CPU from Intel, 60 Mb internet upload

* Client Edition: Win10, Android, IOS

* Client Version: 1.1.2, 1.1.0

### Crashdump, backtrace or other files

* 
```
<!--- Copy and paste your backtrace here... -->
```
* no backtraces on server

**Comment by Creeperface01** [comment]
Duplicated #19
