### ISSUE TITLE
PlayerInteractEvent, BlockBreakEvent,BlockPlaceEvent, etc are not working (1.2 branch)

### ISSUE THREAD

**Issue by Goodstuff4UonYT** [yescallop/Nukkit#59]
### Issue Description

The events are not called.
### Steps to Reproduce the Issue
Break a block and you can see the BlockBreakEvent isn't called.

**Comment by ghost** [comment]
+ Sounds

**Comment by buchwasa** [comment]
Welcome to 1.2, everything needs redone

**Comment by ghost** [comment]
@Goodstuff4UonYT Because packets have encode and decode is incorrect.

@AppleDevelops Yes, need in nukkit.

**Comment by ghost** [comment]
@NycuRO Not everything is caused by packets

**Comment by ghost** [comment]
@PikyCZ Are you sure?

**Comment by ghost** [comment]
yop....

**Comment by PikyCZ** [comment]
https://github.com/yescallop/Nukkit/pull/60

**Comment by Goodstuff4UonYT** [comment]
@PikyCZ @NycuRO Is this WIP?

**Comment by ghost** [comment]
Idk.
