### ISSUE TITLE
Inventory and transactions not working

### ISSUE THREAD

**Issue by kvetinac97** [yescallop/Nukkit#65]
1) When a transaction occurs, it is not sent exactly to the player, block placing and breaking does not work
2) Transaction IDs are messed up
3) In TransactionEvent, you have no way to get inventories/player/chest... in which the transaction occurred.

**Comment by ghost** [comment]
@yescallop

**Comment by ghost** [comment]
https://github.com/pmmp/PocketMine-MP/commits/mcpe-1.2?after=445a67954d214c24b48bdae19fcb5fb4bea431bb+69 ?

**Comment by kvetinac97** [comment]
This is not bug of Nukkit, but the MCPE's one. MCPE sends only halfs of packets, so I hope they'll fix it in the feature.
